inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rails.yml"

inherit_mode:
  merge:
    - Exclude

Rails/SaveBang:
  AllowedReceivers:
    - connection.directories # false positive for Fog::Storage
